export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';

export const SELECT_CONTACT = 'SELECT_CONTACT';
export const UNSELECT_CONTACT = 'UNSELECT_CONTACT';

export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';




